version: '2.0'
kind: agent

execute:
  agent:
    container:
      image: reg.docker.alibaba-inc.com/tonywu6/secretflow-web-ci:20240511-2
    resourceClass: M

  steps:
    - name: download-component
    - name: clone

    - name: shell
      with:
        script: |
          # How is this not built-in?
          export CI=true
          export PATH=$HOME/.cargo/bin:$PATH
          eval `fnm env`

          apt-get update
          apt-get install -y rsync jq

          cd ${CODE_WORKSPACE}

          uv venv
          source .venv/bin/activate

          uv pip install \
            --cache-dir ./node_modules/.pip-cache \
            --index-url https://mirrors.aliyun.com/pypi/simple/ \
            -r ${COMPONENT_WORKSPACE}/docs/requirements.txt \
            ${COMPONENT_WORKSPACE}/vendor/wheelhouse/secretflow-doctools/secretflow_doctools-0.7.2-py3-none-manylinux_2_17_x86_64.whl

          cp ${COMPONENT_WORKSPACE}/docs/conf.py docs/conf.py

          python -m sphinx -T -E -b mdx -j 4 -D language=en \
            docs docs/_build/mdx/en

          python -m sphinx -T -E -b mdx -j 4 -D language=zh_CN \
            docs docs/_build/mdx/zh_CN

          cd ${COMPONENT_WORKSPACE}


          cd ${CODE_WORKSPACE}

          tar czvf mdx.tar.gz -C docs/_build mdx
          tar czvf jsx.tar.gz -C docs/_build jsx

          add_output repo $(jq -j '.["x-secretflow-targets"][0].repo' docs/_build/jsx/package.json)
          add_output ref $(jq -j '.["x-secretflow-targets"][0].ref' docs/_build/jsx/package.json)

    - name: artifact
      with:
        key: mdx
        path: mdx.tar.gz

    - name: artifact
      with:
        key: jsx
        path: jsx.tar.gz

    - name: oss-cache
      with:
        key: pip-cache-{{ checksum 'docs/requirements.txt' }}
        paths: node_modules/.pip-cache
        type: upload

outputs:
  repo:
    value: ${{execute.outputs.repo}}
  ref:
    value: ${{execute.outputs.ref}}
  mdx:
    value: ${{execute.artifacts.mdx}}
  jsx:
    value: ${{execute.artifacts.jsx}}

web:
  type: iframe
  source: https://aci-template-site.alipay.com/secretflow-docs-preview/docs/${{outputs.repo}}/${{outputs.ref}}
  config:
    enableStatus:
      - SUCCESS
    data:
      repo: ${{outputs.repo}}
      ref: ${{outputs.ref}}
